version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "stock-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1pmj8fdzh6j5t"
s3_prefix = "stock-backend"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []