AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  stock_backend

  Sample SAM Template for stock_backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    Runtime: java11
    Architectures:
      - arm64
    MemorySize: 512

Resources:
  StockBackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: StockBackendFunction
      Handler: stock.backend.App::handleRequest
      Events:
        StockBackend:
          Type: Api
          Properties:
            Path: /portfolios
            Method: get

Outputs:

  StockBackendApi:
    Description: "API Gateway endpoint URL for Prod stage for Stock Backend function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/"
  StockBackendFunction:
    Description: "Stock Backend Lambda Function ARN"
    Value: !GetAtt StockBackendFunction.Arn
  StockBackendIamRole:
    Description: "Implicit IAM Role created for Stock Backend function"
    Value: !GetAtt StockBackendFunctionRole.Arn
