AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  stock_backend

  Sample SAM Template for stock_backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    Runtime: java11
    Architectures:
      - arm64
    MemorySize: 512

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.App::handleRequest
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

  BackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: StockBackend
      Handler: stock.backend.App::handleRequest
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        GetPortfolios:
          Type: Api
          Properties:
            Path: /portfolios
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn

  StockBackendApi:
    Description: "API Gateway endpoint URL for Prod stage for Stock Backend function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/stock/backend/portfolios/"
  StockBackendFunction:
    Description: "Stock Backend Lambda Function ARN"
    Value: !GetAtt StockBackend.Arn
  StockBackendIamRole:
    Description: "Implicit IAM Role created for Stock Backend function"
    Value: !GetAtt StockBackendFunctionRole.Arn
